name: Unfollow Non-Followers
on:
  schedule:
    - cron: '0 12,15,18,19,20,21,23 * * *'
  workflow_dispatch:

jobs:
  unfollow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Load environment variables
        run: |
          echo "GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> .env

      - name: Run Go Program
        run: go run cmd/main.go