name: Unfollow Non-Followers
on:
  schedule:
    - cron: '0 9,10,12,15,18,19,20,21,23 * * *'
  workflow_dispatch:

jobs:
  unfollow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true 

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Configure Git user
        run: |
          git config user.name  "GhostBuster"
          git config user.email "ghostbuster@github.com"

      - name: Load environment variables
        run: |
          echo "MY_GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> .env

      - name: Run Go Program
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: go run cmd/main.go
